language: java
jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea
  
dist: trusty

#
# Run all integration tests.
script: 
  - "mvn --show-version --errors --batch-mode clean verify"
# -XX:MaxPermSize in mavenrc deprecated
env: "MAVEN_SKIP_RC=true"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - rfscholte@apache.org
