language: java

# Required to give Java9 a try
sudo: required
dist: trusty
group: edge

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

# No need for preliminary install step.
install: true
#
# Run all integration tests.
script: 
  - "mvn --show-version --errors --batch-mode clean verify"
# -XX:MaxPermSize in mavenrc deprecated
env: "MAVEN_SKIP_RC=true"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - rfscholte@apache.org
